OrderTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: OrderTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: orderPlacedBy
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: buyerEmail
        KeySchema:
          - AttributeName: orderPlacedBy
            KeyType: HASH
        Projection:
          ProjectionType: ALL
